[package]
name = "satp_protos_rs"
version = "0.1.0"
edition = "2018"

[lib]
name = "satp"
path = "src/lib.rs"

[dependencies]
tonic = {version="0.8.3",  features = ["tls"]}
prost = "0.11.8"
serde = {version="1.0.159", features = ["derive"]}