name = "Dummy_Gateway"
port="5001"
hostname="localhost"
db_path="db/Dummy_Gateway/requests"
# max retries opening sled db if it is locked
db_open_max_retries=500
# retry back off time in ms if sled db is locked
db_open_retry_backoff_msec=10

# Networks map is used to identity the network behind the gateway
# by its network name so the request can be routed to the right driver
[networks]
[networks.Dummy_Network]
network="Dummy"

# Location of the remote gateways
[gateways]
[gateways.Dummay_Gateway2]
hostname="localhost"
port="5002"

# host and port of the driver identified by networks map
[drivers]
[drivers.Dummy2]
hostname="localhost"
port="6002"
